services:
  envoy-1.24.0:
    image: jacobneiltaylor/trace-test:1.24.0
    ports: [1240:8080]
    build:
      context: .
      args:
        VERSION: 1.24.0

  envoy-1.23.0:
    image: jacobneiltaylor/trace-test:1.23.0
    ports: [1230:8080]
    build:
      context: .
      args:
        VERSION: 1.23.0

  envoy-1.22.0:
    image: jacobneiltaylor/trace-test:1.22.0
    ports: [1220:8080]
    build:
      context: .
      args:
        VERSION: 1.22.0
      
  envoy-1.21.0:
    image: jacobneiltaylor/trace-test:1.21.0
    ports: [1210:8080]
    build:
      context: .
      args:
        VERSION: 1.21.0

  envoy-1.20.0:
    image: jacobneiltaylor/trace-test:1.20.0
    ports: [1200:8080]
    build:
      context: .
      args:
        VERSION: 1.20.0

  envoy-1.19.0:
    image: jacobneiltaylor/trace-test:1.19.0
    ports: [1190:8080]
    build:
      context: .
      args:
        VERSION: 1.19.0