FROM envoyproxy/envoy-build-ubuntu:b0ff77ae3f25b0bf595f9b8bba46b489723ab446 as envoy-build
RUN sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-$([ $(uname -m) = "aarch64" ] && echo "arm64" || echo "amd64")
RUN sudo chmod +x /usr/local/bin/bazel
RUN mkdir -p /opt/envoy-build
WORKDIR /opt/envoy-build
RUN git clone --depth 1 --branch v1.24.0 https://github.com/envoyproxy/envoy.git .
RUN bazel build -c opt envoy

#FROM golang:1.19.3-alpine3.16 as build
#COPY go.mod go.sum main.go ./
#RUN go mod download && go mod verify
#RUN go build -v -o /tmp/app ./...
#
#FROM envoy:v1.21-latest
#RUN mkdir -p /opt/trace-test/bin
#COPY --from=build /tmp/app /opt/trace-test/bin/
#COPY ./config/envoy.conf.yaml /etc/envoy/envoy.yml